zuul:
  routes:
    service-user-auth:
      path: /user-auth/**
      service-id: service-user-auth
    service-blog:
      path: /blog/**
      service-id: service-blog
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
filter:
  web-auth:
    # 不进行过滤的url
   ignored-mappings: >
     /user-auth/login[post],register-account,/user-auth/clicks-inc,/blog/article/get-article-list,/blog/article/get-article-by-id/*,
     /blog/article/praise-article/*