server:
  port: 6101
spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beFondOfTaro/yazhe-web
          search-paths: config
          default-label: master
          username:
          password: