server:
  port: 6115

spring:
  application:
      name: service-user-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6100/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
