spring:
  datasource:
    url: jdbc:mysql://39.108.97.103:3306/yazhe_web?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  redis:
    host: 39.108.97.103
    port: 6379